config/routes.rb
Rails.application.routes.draw do
  resources :drop_out_predictions
  root to: 'home#index'
  get 'reports', :to => 'home#report'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # dataset = [
    #   {
    #     "Location": "Near",
    #     "%Drop": "Very Low",
    #     "GWA": "Medium",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Far",
    #     "%Drop": "Very High",
    #     "GWA": "Fail",
    #     "Gender": "Male",
    #     "Action": "Drop"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "Medium",
    #     "Gender": "Female",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Far",
    #     "%Drop": "Very High",
    #     "GWA": "Fail",
    #     "Gender": "Female",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Very Far",
    #     "%Drop": "None",
    #     "GWA": "Low",
    #     "Gender": "Male",
    #     "Action": "Drop"
    #   },
    #   {
    #     "Location": "Very Far",
    #     "%Drop": "Very High",
    #     "GWA": "Fail",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "Medium",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "Very High",
    #     "GWA": "Fail",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "Medium",
    #     "Gender": "Female",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "Medium",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "Medium",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "Medium",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Very Far",
    #     "%Drop": "None",
    #     "GWA": "High",
    #     "Gender": "Female",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "Very High",
    #     "GWA": "Fail",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "Very High",
    #     "GWA": "Medium",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "High",
    #     "Gender": "Female",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "High",
    #     "GWA": "Low",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "High",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Very Far",
    #     "%Drop": "Very Low",
    #     "GWA": "Medium",
    #     "Gender": "Female",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "Medium",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "High",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "Medium",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "Medium",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "Very High",
    #     "GWA": "Fail",
    #     "Gender": "Male",
    #     "Action": "Drop"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "High",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Very Far",
    #     "%Drop": "None",
    #     "GWA": "Very High",
    #     "Gender": "Female",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "High",
    #     "Gender": "Female",
    #     "Action": "Drop"
    #   },
    #   {
    #     "Location": "Very Far",
    #     "%Drop": "None",
    #     "GWA": "High",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "Very High",
    #     "Gender": "Female",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "Medium",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Far",
    #     "%Drop": "None",
    #     "GWA": "Low",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "Medium",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "Very Low",
    #     "GWA": "Medium",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Very Far",
    #     "%Drop": "Very High",
    #     "GWA": "Fail",
    #     "Gender": "Male",
    #     "Action": "Drop"
    #   },
    #   {
    #     "Location": "Very Far",
    #     "%Drop": "None",
    #     "GWA": "Medium",
    #     "Gender": "Female",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "High",
    #     "Gender": "Female",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Far",
    #     "%Drop": "Low",
    #     "GWA": "Medium",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Far",
    #     "%Drop": "None",
    #     "GWA": "Medium",
    #     "Gender": "Female",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Far",
    #     "%Drop": "None",
    #     "GWA": "Medium",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "Medium",
    #     "Gender": "Female",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Very Far",
    #     "%Drop": "Very Low",
    #     "GWA": "Medium",
    #     "Gender": "Male",
    #     "Action": "Drop"
    #   },
    #   {
    #     "Location": "Far",
    #     "%Drop": "None",
    #     "GWA": "High",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Far",
    #     "%Drop": "Very High",
    #     "GWA": "Fail",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "Low",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "Very High",
    #     "GWA": "Fail",
    #     "Gender": "Female",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "Very High",
    #     "GWA": "Fail",
    #     "Gender": "Female",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Far",
    #     "%Drop": "Low",
    #     "GWA": "Low",
    #     "Gender": "Female",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "Very High",
    #     "GWA": "Fail",
    #     "Gender": "Male",
    #     "Action": "Drop"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "Medium",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "Medium",
    #     "Gender": "Female",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Far",
    #     "%Drop": "None",
    #     "GWA": "Medium",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Very Far",
    #     "%Drop": "Very High",
    #     "GWA": "Fail",
    #     "Gender": "Male",
    #     "Action": "Drop"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "High",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "Very High",
    #     "GWA": "Fail",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "Low",
    #     "GWA": "Low",
    #     "Gender": "Female",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "High",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Far",
    #     "%Drop": "None",
    #     "GWA": "High",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "High",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "None",
    #     "GWA": "High",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {
    #     "Location": "Near",
    #     "%Drop": "Very High",
    #     "GWA": "Medium",
    #     "Gender": "Male",
    #     "Action": "Continue"
    #   },
    #   {

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
  <%= link_to "Enter New Data", new_drop_out_prediction_path, class: 'home-btn' %>
  <%= link_to "Manage Data", drop_out_predictions_path, class: 'home-btn' %>
  <%= link_to "Generate Report", "/reports", class: 'home-btn' %>
</div>

app/views/home/report.html.erb
<div class="px-5 mx-5">
  <input type="hidden" value="reports" id="location">
  <a href="/" class="btn btn-warning btn-maroon my-3 no-print">Home</a>
  <h3>Report</h3>
  <div class="d-flex">
    <span class="mr-3"><strong>Date: </strong> <%= Date.today.strftime("%B %d, %Y") %></span><br><br>
    <span class="mr-3"><strong>Semister: </strong> <%= params['semister'] || "All" %></span><br><br>
    <span class="mr-3"><strong>School Year: </strong> <%= params['school_year'] || "All" %></span>
  </div>
  <div class="filter-container no-print mb-3">
    <label for="">School Year: </label>
    <select name="" id="school_year">
      <option value="all">All</option>
      <% @semisters.reverse.each do |school_year| %>
        <option <%= params["school_year"] != nil && school_year == params["school_year"] ? "selected" : "" %> value="<%= school_year %>"><%= school_year %></option>
      <% end %>
    </select>
    <label for="">Semester:  </label>
    <select name="" id="semister">
      <option value="all">All</option>
      <% ['1st Semester', '2nd Semester', 'Summer'].each do |school_year| %>
        <option <%= params["semister"] != nil && school_year == params["semister"].split(" ").map(&:capitalize).join(" ") ? "selected" : "" %> value="<%= school_year %>"><%= school_year %></option>
      <% end %>
    </select>
  </div>
  <div class="overflow-auto">
    <table class="table-index">
      <thead>
        <tr>
          <th>Name</th>
          <th>Year</th>
          <th>Course</th>
          <th>Location</th>
          <th>Drop</th>
          <th>Gwa</th>
          <th>Gender</th>
          <th>Prediction</th>
        </tr>
      </thead>
      <tbody>
        <% @drop_out_predictions.each do |drop_out_prediction| %>
          <tr>
            <td><%= drop_out_prediction.name %></td>
            <td><%= drop_out_prediction.year %></td>
            <td><%= drop_out_prediction.course %></td>
            <td><%= drop_out_prediction.location %></td>
            <td><%= drop_out_prediction.drop %></td>
            <td><%= drop_out_prediction.gwa %></td>
            <td><%= drop_out_prediction.gender %></td>
            <td class="<%= drop_out_prediction.action == "DROP" ? "drop" : "continue" %>"><%= drop_out_prediction.action %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <button class="btn btn-warning btn-maroon mt-3 no-print" onclick="window.print()">PRINT</button>

</div>