config/routes.rb
Rails.application.routes.draw do
  resources :drop_out_predictions
  root to: 'home#index'
  get 'reports', :to => 'home#report'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/drop_out_prediction.rb
class DropOutPrediction < ApplicationRecord
  validates :name, presence: true
  validates :year, presence: true
  validates :course, presence: true
  validates :location, presence: true
  validates :drop, presence: true
  validates :gwa, presence: true
  validates :gender, presence: true
end

app/controllers/drop_out_predictions_controller.rb
class DropOutPredictionsController < ApplicationController
  before_action :set_drop_out_prediction, only: [:show, :edit, :update, :destroy]
  before_action :set_semister
  # GET /drop_out_predictions
  # GET /drop_out_predictions.json
  def index
    
    @drop_out_predictions = DropOutPrediction.all
    if (params["school_year"] != "all" && params["school_year"] != nil)
      @drop_out_predictions = @drop_out_predictions.where(school_year: params["school_year"])
    end

    if (params["semister"] != "all" && params["semister"] != nil)
      @drop_out_predictions = @drop_out_predictions.where(semister: params["semister"].split(" ").map(&:capitalize).join(" "))
    end
    @drop_out_predictions = @drop_out_predictions.order(:name)

  end

  # GET /drop_out_predictions/1
  # GET /drop_out_predictions/1.json
  def show
  end

  # GET /drop_out_predictions/new
  def new
    @drop_out_prediction = DropOutPrediction.new
  end

  # GET /drop_out_predictions/1/edit
  def edit
  end

  # POST /drop_out_predictions
  # POST /drop_out_predictions.json
  def create
    @drop_out_prediction = DropOutPrediction.new(drop_out_prediction_params)
    @drop_out_prediction.action = predictAction(@drop_out_prediction)
    respond_to do |format|
      if @drop_out_prediction.save
        format.html { redirect_to @drop_out_prediction, notice: 'Drop out prediction was successfully created.' }
        format.json { render :show, status: :created, location: @drop_out_prediction }
      else
        format.html { render :new }
        format.json { render json: @drop_out_prediction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drop_out_predictions/1
  # PATCH/PUT /drop_out_predictions/1.json
  def update
    respond_to do |format|
      if @drop_out_prediction.update(drop_out_prediction_params)
        @drop_out_prediction.action = predictAction(@drop_out_prediction)
        @drop_out_prediction.save
        format.html { redirect_to @drop_out_prediction, notice: 'Drop out prediction was successfully updated.' }
        format.json { render :show, status: :ok, location: @drop_out_prediction }
      else
        format.html { render :edit }
        format.json { render json: @drop_out_prediction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drop_out_predictions/1
  # DELETE /drop_out_predictions/1.json
  def destroy
    @drop_out_prediction.destroy
    respond_to do |format|
      format.html { redirect_to drop_out_predictions_url, notice: 'Drop out prediction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # set semister list
    def set_semister
      @semisters = []
      (2010..(Date.today().year)).each do |year|
        @semisters.push(year.to_s + "-" + (year + 1).to_s)
      end
      @semisters.reverse
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_drop_out_prediction
      @drop_out_prediction = DropOutPrediction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drop_out_prediction_params
      params.require(:drop_out_prediction).permit(:name, :year, :course, :location, :drop, :gwa, :gender, :action, :school_year, :semister)
    end

    # predict the action of a student
    def predictAction(test)

      gwa     = "Very High"
      p_drop  = "Very High" 
      loc     = "Others"

      if (test.gwa == nil || test.drop == nil )
        return "error"
      end

      if(test.gwa < 75)
        gwa = "Fail"
      elsif (test.gwa < 80)
        gwa = "Low"
      elsif (test.gwa < 85)
        gwa = "Medium"
      elsif (test.gwa < 90)
        gwa = "High"
      else 
        gwa = "Very High"
      end

      if(test.drop <= 15)
        p_drop = "Very Low"
      elsif (test.drop <= 30)
        p_drop = "Low"
      elsif (test.drop <= 60)
        p_drop = "High"
      else 
        p_drop = "Very High"
      end

      if("Others" == test.location)
        loc = "Very Far"
      elsif ("Dagupan City" == test.location || "Mangaldan" == test.location || "Calasiao" == test.location || "Binmaley" == test.location)
        loc = "Near"
      else
        loc = "Far"
      end

      nbayes = YAML.load_file("model.yml")    
      result = nbayes.classify({location: loc, drop: p_drop, gwa: gwa, gender: test.gender})
      r_continue = result["Continue"]
      r_drop = result["Drop"]
      if r_drop > r_continue
        return "DROP"
      else
        return "CONTINUE"
      end
    end
end

app/helpers/drop_out_predictions_helper.rb
module DropOutPredictionsHelper
end

app/views/drop_out_predictions/_form.html.erb
<%= simple_form_for(@drop_out_prediction) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :school_year, collection: @semisters.reverse, include_blank: false  %>
    <%= f.input :semister, label: "Semester", collection: ['1st Semester', '2nd Semester', 'Summer'], include_blank: false  %>
    <%= f.input :name %>
    <%= f.input :year, collection: ['1st', '2nd', '3rd', '4th', '5th', 'Others'], include_blank: false  %>
    <%= f.input :course, collection: ['BSCS', 'BSIT', 'ASSOCIT', 'ASSOCCS'], include_blank: false %>
    <%= f.input :location, collection: ["Dagupan City", "Mangaldan", "Calasiao", "Binmaley",
                         "Bugallon", "Lingayen", "San Carlos City", "Sta. Barbara", "San Jacinto", "Labrador", "Mapandan", "Malasiqui", "Manaoag", "San Fabian",
                         "Others"], include_blank: false %>
    <%= f.input :drop %> 
    <%= f.input :gwa %>
    <%= f.input :gender, collection: ['Male', 'Female'], include_blank: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-warning btn-maroon' %>
  </div>
<% end %>

app/views/drop_out_predictions/edit.html.erb
<div class="form-container">
  <a href="/" class='btn btn-warning btn-maroon'>Home</a><hr>
  <h3>Editing Drop Out Prediction</h3>
  <%= render 'form', drop_out_prediction: @drop_out_prediction %>
</div>

app/views/drop_out_predictions/index.html.erb
<div class="px-5 mx-5">
  <a href="/" class='btn btn-warning btn-maroon'>Home</a><hr>
  <input type="hidden" value="drop_out_predictions" id="location">
  <h3>Manage Data</h3>
  <div class="filter-container">
    <label for="">School Year: </label>
    <select name="" id="school_year">
      <option value="all">All</option>
      <% @semisters.reverse.each do |school_year| %>
        <option <%= params["school_year"] != nil && school_year == params["school_year"] ? "selected" : "" %> value="<%= school_year %>"><%= school_year %></option>
      <% end %>
    </select>
    <label for="">Semester:  </label>
    <select name="" id="semister">
      <option value="all">All</option>
      <% ['1st Semester', '2nd Semester', 'Summer'].each do |school_year| %>
        <option <%= params["semister"] != nil && school_year == params["semister"].split(" ").map(&:capitalize).join(" ") ? "selected" : "" %> value="<%= school_year %>"><%= school_year %></option>
      <% end %>
    </select>
  </div><br>
  
  <div class="overflow-auto">
    <table class="table-index">
      <thead>
        <tr>
          <th>Name</th>
          <th>Year</th>
          <th>Course</th>
          <th>Location</th>
          <th>Drop</th>
          <th>Gwa</th>
          <th>Gender</th>
          <th>Prediction</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @drop_out_predictions.each do |drop_out_prediction| %>
          <tr>
            <td><%= link_to drop_out_prediction.name, drop_out_prediction %></td>
            <td><%= drop_out_prediction.year %></td>
            <td><%= drop_out_prediction.course %></td>
            <td><%= drop_out_prediction.location %></td>
            <td><%= drop_out_prediction.drop %></td>
            <td><%= drop_out_prediction.gwa %></td>
            <td><%= drop_out_prediction.gender %></td>
            <td class="<%= drop_out_prediction.action == "DROP" ? "drop" : "continue" %>"><%= drop_out_prediction.action %></td>
            <td><%= link_to 'Edit', edit_drop_out_prediction_path(drop_out_prediction), class: 'btn btn-sm btn-warning btn-maroon' %> <%= link_to 'Delete', drop_out_prediction, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-warning btn-maroon' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/drop_out_predictions/new.html.erb
<div class="form-container">
  <a href="/" class='btn btn-warning btn-maroon'>Home</a><hr>
  <h3>New Drop Out Prediction</h3>
  <%= render 'form', drop_out_prediction: @drop_out_prediction, semisters: @semisters %>
</div>

app/views/drop_out_predictions/show.html.erb
<div class="px-5 mx-5">
  <p id="notice"><%= notice %></p>
  <a href="/" class='btn btn-warning btn-maroon'>Home</a><hr>

  <h3><%= @drop_out_prediction.name %></h3>
  
  <p>
    <strong>School year:</strong>
    <%= @drop_out_prediction.school_year %>
  </p>
  <p>
    <strong>Semester:</strong>
    <%= @drop_out_prediction.semister %>
  </p>
  <p>
    <strong>Year:</strong>
    <%= @drop_out_prediction.year %>
  </p>

  <p>
    <strong>Course:</strong>
    <%= @drop_out_prediction.course %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= @drop_out_prediction.location %>
  </p>

  <p>
    <strong>Drop:</strong>
    <%= @drop_out_prediction.drop %>
  </p>

  <p>
    <strong>Gwa:</strong>
    <%= @drop_out_prediction.gwa %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= @drop_out_prediction.gender %>
  </p>

  <p>
    <strong>Action:</strong>
    <%= @drop_out_prediction.action %>
  </p>

  <%= link_to 'Edit', edit_drop_out_prediction_path(@drop_out_prediction), class: 'btn btn-sm btn-warning btn-maroon' %>
</div>